version: "3.8"

services:
  # Backend API Server
  backend:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11690216/assignment1:server
    container_name: video-transcriber-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/data
    ports:
      - "5000:8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  # Frontend Client
  frontend:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11690216/assignment1:client
    container_name: video-transcriber-frontend
    restart: unless-stopped
    ports:
      - "8080:5173"
    environment:
      - .env
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
